// Generated by CoffeeScript 1.7.1
(function() {
  var addPopup, detailView, glanceView, init, mapContainerTemplate, popupTemplate, toggleView;

  mapContainerTemplate = '<div class="map-container bg-<%= color %>" id="map-<%= index %>">\n  <h2 style="font-size: 72px; text-align: center"><%= index %></h2>\n  Pork belly hella stumptown vinyl, kitsch trust fund drinking vinegar. Post-ironic asymmetrical pork belly, High Life pickled DIY Cosby sweater tofu ethnic actually bitters. Tonx biodiesel squid normcore stumptown. Normcore Kickstarter selfies gentrify church-key. Farm-to-table Williamsburg meh keytar. Hoodie post-ironic +1 synth. Banh mi before they sold out Williamsburg aesthetic fanny pack ethical squid.\n</div>';

  popupTemplate = '<div class="popup bg-gray">\n  <%= popupContent %>\n</div>';

  toggleView = function($container, targetNode) {
    if ($container.hasClass('detail-view')) {
      if (targetNode.id === 'map-footer') {
        glanceView($container, targetNode);
        return $container.toggleClass('detail-view');
      }
    } else {
      detailView($container, targetNode);
      return $container.toggleClass('detail-view');
    }
  };

  detailView = function($container, targetNode) {
    var translateDistance;
    translateDistance = 0;
    _.forEach($('.map-container'), function(mapContainer, index) {
      var $mapContainer;
      $mapContainer = $(mapContainer);
      translateDistance += $mapContainer.height() / 4;
      return $mapContainer.transition({
        perspective: 500,
        rotateX: 0,
        width: '200%',
        height: '200%'
      });
    });
    $container.css('overflow-x', 'scroll').append('<div id="map-footer" class="bg-white">Back to glance view</div>');
    window.location.hash = targetNode.id;
    return $container;
  };

  glanceView = function($container) {
    $('#map-footer').remove();
    $container.scrollLeft(0);
    _.forEach($('.map-container'), function(mapContainer) {
      var $mapContainer;
      $mapContainer = $(mapContainer);
      return $mapContainer.transition({
        perspective: 500,
        rotateX: 30,
        width: '100%',
        height: '100%'
      });
    });
    return $container.css('overflow-x', 'hidden');
  };

  addPopup = function($triggerNode, popupContent, popupWidth, popupHeight) {
    var popup;
    if (popupWidth == null) {
      popupWidth = 200;
    }
    if (popupHeight == null) {
      popupHeight = 200;
    }
    popup = _.template(popupTemplate, {
      popupContent: popupContent
    });
    return $triggerNode.hammer().on('tap', function(ev) {
      var $popup, popupLeft, popupTop;
      $popup = $(popup).width(popupWidth).height(popupHeight);
      if ($('.popup').length > 0) {
        $('.popup').remove();
      }
      popupLeft = ev.gesture.center.pageX;
      popupTop = ev.gesture.center.pageY;
      if (popupLeft + popupWidth > $('body').width()) {
        popupLeft -= popupWidth;
      }
      if (popupTop + popupHeight > $('body').height()) {
        popupTop -= popupHeight;
      }
      $popup.css('left', popupLeft);
      $popup.css('top', popupTop);
      return $('#popups').append($popup);
    });
  };

  init = function($container) {
    $container.hammer().on('tap', function(ev) {
      return toggleView($container, ev.target);
    });
    ['blue', 'green', 'yellow', 'orange', 'red', 'purple'].forEach(function(color, index) {
      var $map;
      $map = $(_.template(mapContainerTemplate, {
        color: color,
        index: index + 1
      }));
      $container.append($map);
      return addPopup($map, 'Foo bar');
    });
    return glanceView($container);
  };

  init($('#container'));

}).call(this);
